service: hack

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1
  stage: ${opt:stage}
  stackTags:
    PROJECT: ${self:service}
    STAGE: ${self:provider.stage}
    SERVICE: "40"

plugins:
  - serverless-iam-roles-per-function
  - serverless-pseudo-parameters

functions:
  hello:
    handler: functions/handler.hello
    events:
      - http: GET hello

resources:
  Resources:
    ParkingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: parking_area_current-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
