service: hack

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1
  stage: ${opt:stage}
  stackTags:
    PROJECT: ${self:service}
    STAGE: ${self:provider.stage}
    SERVICE: "40"

plugins:
  - serverless-iam-roles-per-function
  - serverless-pseudo-parameters

functions:
  hello:
    handler: functions/handler.hello
    events:
      - http: GET hello

resources:
- ${file(resources/dynamodb-table.yml)}
