  Resources:
    ParkingTable:
      Type: AWS::DynamoDB::Table
      BillingMode: PAY_PER_REQUEST
      Properties:
        TableName: parking_area_current-${self:provider.stage}-${self:custom.name}
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH